version: 2


seeds:
  - name: lkp_divisions
    config:
      schema : LKPDATA
 
  - name: lkp_categories
    config:
      schema : LKPDATA
 
  - name: lkp_shippers
    config:
      schema : LKPDATA

  - name: lkp_officces
    config:
      schema : LKPDATA    
